version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: excellent_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    expose:
      - "9000"
    networks:
      - app-network

  web:
    build:
      context: ./nginx
    container_name: excellent_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: appkr/mysql:5.7-arm64
    container_name: excellent_db
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: excellent
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: excellent_frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
